import json
import numpy as np
import faiss
import torch
import warnings

class KnowledgeRetriever:
    """
    KnowledgeRetriever module: performs high-speed similarity search between EEG semantic queries (Q_t)
    and pre-computed biomedical knowledge embeddings using FAISS.

    Each EEG node query vector retrieves top-k semantically similar triplets (head, relation, tail)
    from the knowledge graph, enabling RAG-based contextual refinement of dynamic brain graphs.
    """

    def __init__(self, index_path: str, kg_json_path: str, k: int = 5, normalize: bool = True):
        """
        Initialize the KnowledgeRetriever.

        Args:
            index_path (str): Path to FAISS index file.
            kg_json_path (str): Path to JSON file containing triplets and embeddings.
            k (int): Number of top results to retrieve per query.
            normalize (bool): Whether to normalize query vectors before search.
        """
        self.index_path = index_path
        self.kg_json_path = kg_json_path
        self.k = k
        self.normalize = normalize

        # Load FAISS index
        self.index = faiss.read_index(index_path)

        # Load knowledge entries. Accept both:
        # 1) flat triplet list [{"head","relation","tail"}, ...]
        # 2) page-level list [{"page_id", "triplets":[...]}]
        with open(kg_json_path, "r", encoding="utf-8") as f:
            raw_kg = json.load(f)

        self.kg = self._to_flat_triplets(raw_kg)

        # Ensure alignment between FAISS vectors and knowledge entries
        if len(self.kg) != self.index.ntotal:
            raise ValueError(
                f"Mismatch: KG entries ({len(self.kg)}) != FAISS index vectors ({self.index.ntotal})"
            )

    @staticmethod
    def _normalize_triplet(head, relation, tail):
        return {
            "head": str(head).strip().lower() if head is not None else "",
            "relation": str(relation).strip().lower() if relation is not None else "",
            "tail": str(tail).strip().lower() if tail is not None else "",
        }

    def _to_flat_triplets(self, raw_kg):
        """Convert knowledge JSON into flat, index-aligned triplets."""
        if not isinstance(raw_kg, list):
            raise ValueError(f"Expected list in KG JSON, got {type(raw_kg)}")

        flat = []
        page_schema_detected = False

        for item in raw_kg:
            # Case 1: already flat triplet
            if isinstance(item, dict) and {"head", "relation", "tail"}.issubset(item.keys()):
                t = self._normalize_triplet(item.get("head"), item.get("relation"), item.get("tail"))
                if t["head"] and t["tail"]:
                    flat.append(t)
                continue

            # Case 2: page-level object with triplets list
            if isinstance(item, dict) and isinstance(item.get("triplets"), list):
                page_schema_detected = True
                page_id = item.get("page_id")
                for tri in item["triplets"]:
                    if not isinstance(tri, dict):
                        continue
                    if not {"head", "relation", "tail"}.issubset(tri.keys()):
                        continue
                    t = self._normalize_triplet(tri.get("head"), tri.get("relation"), tri.get("tail"))
                    if t["head"] and t["tail"]:
                        t["source_page"] = page_id
                        flat.append(t)

        if page_schema_detected:
            warnings.warn(
                "Detected page-level KG schema; auto-flattened triplets for retrieval. "
                "For stable id alignment, prefer using KG_triplets_flat.json generated by build_biobert_faiss.py."
            )

        if not flat:
            raise ValueError("No valid triplets found after KG normalization.")

        return flat

    def _prepare_query(self, Q: torch.Tensor):
        """
        Convert torch tensor to numpy and normalize if required.

        Args:
            Q (torch.Tensor): EEG semantic query embeddings (batch_size, num_nodes, proj_dim)

        Returns:
            Tuple[np.ndarray, Optional[Tuple[int, int]]]:
                - Query matrix (N, D)
                - Original (batch_size, num_nodes) shape if Q is 3D, else None
        """
        original_shape = None
        if Q.dim() == 3:
            original_shape = (Q.size(0), Q.size(1))
            Q = Q.reshape(-1, Q.size(-1))  # Flatten batch and node dims
        Q_np = Q.detach().cpu().numpy().astype("float32")
        if Q_np.shape[1] != self.index.d:
            raise ValueError(
                f"Query dim ({Q_np.shape[1]}) != FAISS index dim ({self.index.d}). "
                "Rebuild index/projection so dimensions match."
            )
        if self.normalize:
            faiss.normalize_L2(Q_np)
        return Q_np, original_shape

    def retrieve(self, Q: torch.Tensor):
        """
        Perform batched FAISS search for the top-k most similar knowledge entries per EEG node query.

        Args:
            Q (torch.Tensor): EEG semantic query embeddings (batch_size, num_nodes, proj_dim)

        Returns:
            List[List[dict]]: For each EEG node query, a list of top-k triplets with similarity scores.
        """
        Q_np, original_shape = self._prepare_query(Q)
        D, I = self.index.search(Q_np, self.k)  # D: distances, I: indices

        retrieved_all = []
        for node_idx, (distances, indices) in enumerate(zip(D, I)):
            node_results = []
            for d, idx in zip(distances, indices):
                if idx < len(self.kg):
                    entry = self.kg[idx]
                    node_results.append({
                        "head": entry.get("head", None),
                        "relation": entry.get("relation", None),
                        "tail": entry.get("tail", None),
                        "source": entry.get("source", ""),
                        "source_type": entry.get("source_type", ""),
                        "reliability": entry.get("reliability", None),
                        "similarity": float(d)
                    })
            retrieved_all.append(node_results)

        # Prefer explicit batched structure: [batch][node][top-k]
        if original_shape is not None:
            batch_size, num_nodes = original_shape
            if len(retrieved_all) != batch_size * num_nodes:
                raise ValueError(
                    f"Retrieved entries ({len(retrieved_all)}) != B*N ({batch_size * num_nodes})."
                )
            batched = []
            for b in range(batch_size):
                start = b * num_nodes
                batched.append(retrieved_all[start:start + num_nodes])
            return batched

        # Backward-compatible unbatched output
        return retrieved_all


if __name__ == "__main__":
    # Example test: assumes FAISS index and KG JSON already exist
    index_path = "knowledge/faiss.index"
    kg_json_path = "knowledge/kg_triplets.json"

    # Create a fake query tensor (batch_size=1, num_nodes=5, proj_dim=256)
    Q = torch.randn(1, 5, 256)

    retriever = KnowledgeRetriever(index_path, kg_json_path, k=3)
    results = retriever.retrieve(Q)

    # Print top-1 retrieved relation for each node
    for i, node_results in enumerate(results):
        top1 = node_results[0] if node_results else None
        print(f"Node {i} top-1:", top1)
